### ISSUE TITLE
FR make `org-link-insert` default description be the current selection

### ISSUE THREAD

**Issue by bricewge** [Somelauw/evil-org-mode#103]
When in visual mode with some text selected, it would be nice to have that selection be the default link description when calling `org-link-insert`.

It looks like it could be done by defining `org-link-make-description-function` to an appropriate function.

Feel free to close this feature request, if it's out of scope of this project.

**Comment by Somelauw** [comment]
I agree, but it would probably make more sense to have such a function in org-mode itself.
