### ISSUE TITLE
`^` doesn't jump to the first non-blank character

### ISSUE THREAD

**Issue by duianto** [Somelauw/evil-org-mode#11]
### Description:
`^` doesn't work as expected, currently it duplicates the behaviour of pressing `0`.

### Expected behaviour:
Pressing `^` should move the cursor to the current lines first non-blank character.

### Actual behaviour:
Pressing `^` moves the cursor to the beginning of the current line.

### Cause:
`^` is bound to `org-beginning-of-line` in this function:
`evil-org--populate-base-bindings`
https://github.com/Somelauw/evil-org-mode/blob/master/evil-org.el#L493

This function only moves the cursor to the beginning of the line when `^` is pressed.

### Possible solution:
Removing the current `^` and `$` bindings from: 
`evil-org--populate-base-bindings`

Restores them to the default evil behaviour:
`^` `evil-first-non-blank` and `$` `evil-end-of-line`

### Additional notes:

`org-beginning-of-line` has an alternate behaviour when the variable `org-special-ctrl-a/e` is set to `t`. That makes `C-a` toggle the cursor between the current lines beginning and the first non-blank character.

A similar behaviour occurs when `C-e` is pressed (in the default emacs state). Then the cursor jumps between the end of the headline and the end of the tag(s).

The `org-{beginning,end}-of-line` functions only seems to check for the key bindings `C-a` and `C-e`, therefore these functions alternate behaviour won't work with the evil bindings `^` and `$`.

**Comment by Somelauw** [comment]
Thanks for you feedback. At least for me setting org-special-ctrl-a/e works even if these functions are bound to ^ and $, so I think they do something useful.
But you are right that when org-special-ctrl-a/e is unset, ^ behaves the same as 0.
Would it help to let ^ keep its current behaviour when on a heading, but to make it jump to the first non-whitespace char when not on a heading?

**Comment by duianto** [comment]
Your right, I missed that when `org-special-ctrl-a/e` is set to `t`, then `^` does jump between the beginning and first character on a heading.

I must only have tested `^` (with the `org-special-ctrl-a/e` variable set to `t`), on the text inside a heading, where I first noticed the issue (My bad 👎). There it only jumps to the beginning.

Now I also noticed that `$` stops at the last character in the heading once, then it jumps to the end of the tags and doesn't jump back when pressed again. I don't know if this is such a huge issue, at least it stops at the end of the heading once.

This might have to do with the evil cursor stopping on the last character, compared to the Emacs state cursor which moves to the right of the last character when `C-e` is pressed in Emacs state. That might be why the `org-end-of-line` function doesn't detect the evil cursor at the end of the line.

>Would it help to let ^ keep its current behaviour when on a heading,

Yes, the current behaviour can be left alone on headings, since there actually are characters at the beginning and end of the line, meaning that the default evil behaviour of `^` jumping to the first character and `$` jumping to the last character, works as expected.

The main issue is on non heading text.

**Comment by Somelauw** [comment]
@duianto 

The simplest solution was to bind org-beginning-of-heading to 0 instead of ^. Then by default 0 and $ behave like in Vim, but the user can modify org-special-ctrl-a/e. It also restores the symmetry between 0 and $.

I have done this in https://github.com/Somelauw/evil-org-mode/commit/a647aae9655058a9381fd512ff3c2ff940481267

**Comment by Somelauw** [comment]
> Possible solution to the special $ behaviour of stopping on the tags last character

Something like that could work, but this rule needs some exceptions. For example, it should leave the behaviour as is when using this on a headline with hidden contents, because it's already working in that case.

> Possible indentation correction

Thanks. I've fixed that.

**Comment by Somelauw** [comment]
I think with commit https://github.com/Somelauw/evil-org-mode/commit/bc1c0446b49fb53b281ec66e75506e08a5c6d3a8 `$` can jump between tags and heading without problem.

**Comment by duianto** [comment]
Confirmed, it works with all 4 scenarios of `evil-move-cursor-back` and `evil-move-beyond-eol` set to `t` or `nil`. Thanks
