### ISSUE TITLE
Make org-agenda more Evil

### ISSUE THREAD

**Issue by Ambrevar** [Somelauw/evil-org-mode#15]
Org-agenda does not have any Evil bindings.  It bugs me to press `n`/`p` just for that buffer.  Any
plan in that area?

**Comment by Somelauw** [comment]
Not yet, but I would be okay with adding an `evil-org-agenda-mode` at some point.

For now, you can put the following in your config:
```emacs-lisp
(define-key org-agenda-mode-map "k" 'org-agenda-previous-line)
(define-key org-agenda-mode-map "j" 'org-agenda-next-line)
```

You can also have a look at https://github.com/mohsenil85/evil-evilified-state for a quick way to rebind keys without losing functionality.

**Comment by Ambrevar** [comment]
I've given a first shot to setting up the bindings, but hell, it's a herculean task!
Here is a first draft:

```
(evil-set-initial-state 'org-agenda-mode 'motion)
(evil-define-key 'motion org-agenda-mode-map
  (kbd "TAB") 'org-agenda-goto
  (kbd "RET") 'org-agenda-switch-to
  (kbd "SPC") 'org-agenda-show-and-scroll-up
  (kbd "DEL") 'org-agenda-show-scroll-down
  (kbd "<backspace>") 'org-agenda-show-scroll-down
  "dd" 'org-agenda-kill
  "u" 'org-agenda-undo
  "!" 'org-agenda-toggle-deadlines
  "zd" 'org-agenda-dim-blocked-tasks
  "za" 'org-agenda-archive
  "zr" 'org-agenda-bulk-mark-regexp
  "zm" 'org-agenda-bulk-mark-all
  "+" 'org-agenda-priority-up
  "-" 'org-agenda-priority-down
  ;; "," 'org-agenda-priority
  "." 'org-agenda-goto-today
  (kbd "M-sf") 'org-agenda-filter-by-tag
  "s" 'org-agenda-set-tags
  "S" 'org-agenda-set-timer
  "<" 'org-agenda-filter-by-category
  "=" 'org-agenda-filter-by-regexp
  ">" 'org-agenda-date-prompt
  "zf" 'org-agenda-show-the-flagging-note
  "A" 'org-agenda-append-agenda
  "zb" 'org-agenda-bulk-action
  "C" 'org-agenda-convert-date
  "D" 'org-agenda-toggle-diary
  "ge" 'org-agenda-entry-text-mode
  "zf" 'org-agenda-follow-mode
  "zg" 'org-agenda-toggle-time-grid
  "gh" 'org-agenda-holidays
  "I" 'org-agenda-clock-in
  "O" 'org-agenda-clock-out
  "J" 'org-agenda-clock-goto
  ;; "L" 'org-agenda-recenter
  "gm" 'org-agenda-phases-of-moon
  (kbd "C-j") 'org-agenda-next-item
  (kbd "C-k") 'org-agenda-previous-item
  ;; "Q" 'org-agenda-quit
  "q" 'org-agenda-quit
  "R" 'org-agenda-clockreport-mode
  "gs" 'org-agenda-sunrise-sunset
  "gi" 'org-agenda-show-tags
  "zM" 'org-agenda-bulk-unmark-all
  "X" 'org-agenda-clock-cancel
  "[" 'org-agenda-manipulate-query-add
  "]" 'org-agenda-manipulate-query-subtract
  "z^" 'org-agenda-filter-by-top-headline
  "z_" 'org-agenda-filter-by-effort
  "a" 'org-agenda-archive-default-with-confirmation
  (kbd "M-h") 'org-agenda-earlier
  (kbd "M-l") 'org-agenda-later
  "c" 'org-agenda-goto-calendar
  ;; "d" 'org-agenda-day-view
  ;; "se" 'org-agenda-set-effort
  "gr" 'org-agenda-redo-all
  (kbd "C-r") 'org-agenda-redo
  "i" 'org-agenda-diary-entry
  "gd" 'org-agenda-goto-date
  "zk" 'org-agenda-capture
  "zl" 'org-agenda-log-mode
  ;; "zm" 'org-agenda-bulk-mark
  "j" 'org-agenda-next-line
  "k" 'org-agenda-previous-line
  ;; "s" 'org-save-all-org-buffers
  "gt" 'org-agenda-todo
  ;; "zM" 'org-agenda-bulk-unmark
  "zv" 'org-agenda-view-mode-dispatch
  "gw" 'org-agenda-week-view
  "Q" 'org-agenda-exit
  "gy" 'org-agenda-year-view
  ;; "za" 'org-agenda-add-note
  "{" 'org-agenda-manipulate-query-add
  "|" 'org-agenda-filter-remove-all ; goto-column?
  "}" 'org-agenda-manipulate-query-subtract
  "~" 'org-agenda-limit-interactively ; invert-char?
  "H" 'org-agenda-do-date-earlier
  "J" 'org-agenda-priority-down
  "K" 'org-agenda-priority-up
  "L" 'org-agenda-do-date-later
  (kbd "M-H") 'org-agenda-todo-previousset
  (kbd "M-J") 'org-agenda-drag-line-forward
  (kbd "M-K") 'org-agenda-drag-line-backward
  (kbd "M-L") 'org-agenda-todo-nextset)
```

I've left some keys commented as I'm undecided about them or they conflict with other bindings.

**Comment by Somelauw** [comment]
Thanks.

Here are some thoughts about how I think bindings should be created:
- Create bindings that make sense to evil users
- Follow conventions in similar packages such as https://github.com/emacs-evil/evil-ediff and https://github.com/emacs-evil/evil-magit
- Follow conventions in `evil-org`
- Stay close to the original bindings

I've thought a little about the bindings before and had come up with the following ones:

```emacs-lisp
(defvar evil-org-agenda-mode-map
  (make-sparse-keymap
   ;; Motion
   "j" 'org-agenda-next-line            ; n
   "k" 'org-agenda-previous-line        ; p
   "l" 'org-agenda-later                ; f
   "h" 'org-agenda-earlier              ; b
   "J" 'org-agenda-next-item            ; N
   "K" 'org-agenda-previous-item        ; P

   ;; Dragging up and down
   (kbd "M-j") 'org-agenda-drag-line-forward  ; M-down
   (kbd "M-k") 'org-agenda-drag-line-backward ; M-up

   ;; View
   "f" 'org-agenda-recenter             ; M
   "F" 'org-agenda-follow-mode

   ;; Change display
   "gd" 'org-agenda-goto-date           ; j
   "gc" 'org-agenda-clock-goto          ; J
   ;; 'org-agenda-toggle-time-grid ;G

   ;; marking (with as few keybindings as possible)
   "m" 'org-agenda-bulk-toggle           ; M-m (m, u)
   "M" 'org-agenda-bulk-toggle-all       ; M-*
   "*" 'org-agenda-bulk-mark-all         ; *
   "U" 'org-agenda-bulk-remove-all-marks ; U
   "%" 'org-agenda-bulk-mark-regexp      ; %
   "b" 'org-agenda-bulk-action           ; B

   ;; Editing
   "gr" 'org-agenda-redo                ; g
   "u" 'org-agenda-undo                 ; C-_
   ;; org-agenda-kill ; C-k
   ;; org-agenda-set-tags ; :

   ;; Other
   "H" 'org-agenda-holidays             ; h
   ))

```

By the way, I think it's okay to overwrite keys like `m`, `t` and `f` as they are not very useful in agenda mode, so you don't need `gt` for `org-agenda-todo`, because `t` is already bound by default and I think you don't need horizontal movement in org-agenda anyway. Just make `j`, `k` `g`, `G`, `C-o`, `C-i` and some other common ones work and leave the rest to org-mode.

**Comment by Ambrevar** [comment]
Thanks for the feedback.  I'll definitely get some inspiration from your bindings.

As for overriding standard keys:
- Horizontal movements might not be so useful in org-agenda, but when you need them (say for copying a word), it can be annoying to have them missing.  Evil-magit works around this with `evil-magit-toggle-text-mode`, but having _modes_ in special modes might just be an additional cognitive burden.

- Some for marks (`m`), although we could argue they are less important than horizontal movements.

**Comment by Somelauw** [comment]
> Evil-magit works around this with evil-magit-toggle-text-mode, but having modes in special modes might just be an additional cognitive burden.

I never felt like I missed them in evil-magit, but otherwise it can be an option. In case horizontal movement is added, would `h` and `l` be enough? You can always use Emacs standard shortcuts or arrow keys. Most of the navigation commands are rarely useful in org-agenda, but they do take up good key spots.

> Some for marks (m), although we could argue they are less important than horizontal movements.

They could be useful if they actually create a mark to a specific time or day, but if they just mark the agenda buffer, I don't think they have much benefit.

**Comment by Ambrevar** [comment]
Side question: why defining a separate map?

**Comment by Ambrevar** [comment]
I've given it another shot, this time taking a much more tidy approach like yours:

```
(evil-define-key 'motion org-agenda-mode-map
  ;; TODO: Bind date selection from miniprompt to S-<hjkl>.
  ;; TODO: Unused keys: D, x, X, o, p, P

  (kbd "<tab>") 'org-agenda-goto
  (kbd "<return>") 'org-agenda-switch-to
  (kbd "S-<return>") 'org-agenda-recenter

  (kbd "<space>") 'org-agenda-show-and-scroll-up
  (kbd "<delete>") 'org-agenda-show-scroll-down
  (kbd "<backspace>") 'org-agenda-show-scroll-down

  ;; Motion
  "j" 'org-agenda-next-line
  "k" 'org-agenda-previous-line
  (kbd "]") 'org-agenda-earlier
  (kbd "[") 'org-agenda-later
  (kbd "C-k") 'org-agenda-previous-item
  (kbd "C-j") 'org-agenda-next-item

  ;; Manipulation
  ;; We follow standard org-mode bindings (not org-agenda bindings):
  ;; <HJKL> change todo items and priorities.
  ;; M-<jk> drag lines.
  ;; M-<hl> cannot demote/promote, we use it for "do-date".
  "H" 'org-agenda-todo-previousset
  "L" 'org-agenda-todo-nextset
  "J" 'org-agenda-priority-down
  "K" 'org-agenda-priority-up
  (kbd "M-j") 'org-agenda-drag-line-forward
  (kbd "M-k") 'org-agenda-drag-line-backward
  (kbd "M-h") 'org-agenda-do-date-earlier
  (kbd "M-l") 'org-agenda-do-date-later

  ;; Undo
  "u" 'org-agenda-undo
  "U" 'org-agenda-redo-all
  (kbd "C-r") 'org-agenda-redo

  ;; Actions
  "dd" 'org-agenda-kill
  "dA" 'org-agenda-archive
  "da" 'org-agenda-archive-default-with-confirmation
  "st" 'org-agenda-set-tags
  "se" 'org-agenda-set-effort
  "S" 'org-timer-set-timer
  "i" 'org-agenda-diary-entry
  "a" 'org-agenda-add-note
  "A" 'org-agenda-append-agenda
  "C" 'org-agenda-capture

  ;; Marking
  "mm" 'org-agenda-bulk-toggle
  "mM" 'org-agenda-bulk-toggle-all
  "m%" 'org-agenda-bulk-mark-regexp
  "mu" 'org-agenda-bulk-remove-all-marks
  "ma" 'org-agenda-bulk-action

  ;; Quit
  "ZQ" 'org-agenda-exit
  "ZZ" 'org-agenda-quit

  ;; Display
  ;; "Dispatch" can prefix the following:
  ;; 'org-agenda-toggle-deadlines
  ;; 'org-agenda-toggle-diary
  ;; 'org-agenda-follow-mode
  ;; 'org-agenda-log-mode
  ;; 'org-agenda-entry-text-mode
  ;; 'org-agenda-toggle-time-grid
  ;; 'org-agenda-day-view
  ;; 'org-agenda-week-view
  ;; 'org-agenda-year-view
  "z" 'org-agenda-view-mode-dispatch
  "ZD" 'org-agenda-dim-blocked-tasks

  ;; Filter
  "fc" 'org-agenda-filter-by-category
  "fr" 'org-agenda-filter-by-regexp
  "fe" 'org-agenda-filter-by-effort
  "ft" 'org-agenda-filter-by-tag
  "fu" 'org-agenda-filter-remove-all
  "f^" 'org-agenda-filter-by-top-headline
  "~" 'org-agenda-limit-interactively

  ;; Clock
  "I" 'org-agenda-clock-in
  "O" 'org-agenda-clock-out
  "cg" 'org-agenda-clock-goto
  "cc" 'org-agenda-clock-cancel
  "cr" 'org-agenda-clockreport-mode

  ;; Go and show
  "." 'org-agenda-goto-today ; TODO: What about evil-repeat?
  "gc" 'org-agenda-goto-calendar
  "gC" 'org-agenda-convert-date
  "gd" 'org-agenda-goto-date
  "gh" 'org-agenda-holidays
  "gm" 'org-agenda-phases-of-moon
  "gs" 'org-agenda-sunrise-sunset
  "gt" 'org-agenda-show-tags

  ;; Others
  "+" 'org-agenda-manipulate-query-add
  "-" 'org-agenda-manipulate-query-subtract
  ;; TODO: Work out the following.
  ;; 'org-save-all-org-buffers
  ;; 'org-agenda-date-prompt
  ;; 'org-agenda-show-the-flagging-note
  )
```

- Do you know what the last two commands are for?  Is `org-save-all-org-buffers really useful?
- I've mapped HJKL to changing priorities and TODO states, just like Org-mode does (but not org-agenda).  No need to override `t` then.
- I liked your idea about marking, but I dislike that you use `b`, `U`, `*`, `M`... Too many Evil bindings gone too fast! :)  What I dislike about mine is that they are somewhat long (since you like them short).  But we still have `x`, `X`, `p` and `P` free.  So what about:

```
  ;; Marking
  "m" 'org-agenda-bulk-toggle
  "p" 'org-agenda-bulk-toggle-all
  "P" 'org-agenda-bulk-mark-regexp
  "X" 'org-agenda-bulk-remove-all-marks
  "x" 'org-agenda-bulk-action
```

I really like where this is getting.  Would you consider a PR once the TODOs are fixed?

**Comment by Somelauw** [comment]
> I've mapped HJKL to changing priorities and TODO states, just like Org-mode does (but not org-agenda). No need to override t then.

Some people want `t` to work even in `org-mode` https://github.com/syl20bnr/spacemacs/issues/8640, it could be something optional. By the way, you are already binding `f`.

> I really like where this is getting. Would you consider a PR once the TODOs are fixed?

Our bindings are converging in some ways, but there are still some differences. Maybe this can be solved by having an option to make `t`, `f`, `b`, `w`, `*` and some others behave like `evil`(your preference) or `org-agenda`(my preference). To me the following Evil bindings are essential and I'm meh on everything else:
```
j, k, C-o, C-i, gg, G, u, C-r, :
h, l, v, V (maybe useful)
```

If you create a pull request make sure to:
- Create a file evil-org-agenda.el
- Have a minor mode that can be enabled / disabled
- Don't import anything from evil-org.el. If put on melpa, I think this should be a separate package.


> I liked your idea about marking, but I dislike that you use b, U, *, M...

Maybe keep `m` and put the rest under `zM`, `zU`, `z*`, etc.

> "z" 'org-agenda-view-mode-dispatch

Not sure if practical, but if you make `g` the dispatcher, it would create some mnemonic keybindings such as `gy` for "goto year". But if difficult, `gg` and `gr` are more important.

**Comment by Somelauw** [comment]
What's might be the most difficult decision first is whether to start from `org-agenda-map`  and add evil bindings (what I am currently doing) or to start from `evil-motion-state` and add org-agenda bindings (what you are currently doing).

This makes a difference for keys that are not explicitly defined.

**Comment by Ambrevar** [comment]
> To me the following Evil bindings are essential and I'm meh on everything else:
> 
> j, k, C-o, C-i, gg, G, u, C-r, :
> h, l, v, V (maybe useful)

- My approach does that automatically.
- Another pro of my approach: somewhat less code (no need to set anything up).
- Your last comment seems to say you like my approach better.

Conclusion: since both ways are more or less 50/50 and we have to take a decision, let's go for my approach.  It will also be interesting to confront this choice with evil-magit and evil-diff and see which one requires more maintenance.

> Maybe keep m and put the rest under zM, zU, z*, etc.
You did not like the following suggestion?
```elisp
  ;; Marking
  "m" 'org-agenda-bulk-toggle
  "p" 'org-agenda-bulk-toggle-all
  "P" 'org-agenda-bulk-mark-regexp
  "X" 'org-agenda-bulk-remove-all-marks
  "x" 'org-agenda-bulk-action
```

> if put on melpa, it should be a different recipe.
Why? I believe that if you want evil-org, you'd expect org-agenda to work out-of-the-box.
For those who do not use org-agenda, they can leave out `(require 'evil-org-agenda)`.

> Not sure if practical, but if you make g the dispatcher, it would create some mnemonic keybindings such as gy for "goto year". But if difficult, gg and gr are more important.

Looking at the dispatcher code, everything is hard-coded, so this does not seem doable.  Nevertheless, the role of the dispatcher is not to "go to" but to display: `zy` does not go to a year, it merely display all entries for the current year.

What is `gr`?

> Maybe this can be solved by having an option to make t, f, b, w, * and some others behave like evil(your preference) or org-agenda(my preference). 

I know evil-org has options and that is arguably a good idea considering the complexity of the issue (org-mode being one of the few modes that is "special" without being a `special mode`).  Org-agenda is not editable however, so I don't think there is a need for it.
Adding options will increase the code complexity and its maintenance, while it is straightforward for the end users to tweak the bindings themselves. If they want `f` or `t` to do something different, it's just one or two lines in their `init.el`, which is just as much as toggling some dedicated option on/off :)

**Comment by Ambrevar** [comment]
That being said, I think setting `t` to `org-agenda-todo` is a good idea: I'll revert it to `evil-find-char-to` in my config :)

**Comment by Somelauw** [comment]
> Your last comment seems to say you like my approach better.

The advantage of using `org-agenda` as a base is that you are sure of all org-agenda commands. The advantage of using `evil-motion-state-map` is that you are sure of all evil commands. As long as all `org-agenda` commands are available it can be both.

> Conclusion: since both ways are more or less 50/50 and we have to take a decision, let's go for my approach. It will also be interesting to confront this choice with evil-magit and evil-diff and see which one requires more maintenance.

For now, we can take your approach.

> You did not like the following suggestion?

I think `m`, `b`, `*` are easy to remember (`m` for mark, `b` for bulk, `*` for all), but `p` and `x` don't have such connections.

> Why? I believe that if you want evil-org, you'd expect org-agenda to work out-of-the-box. For those who do not use org-agenda, they can leave out (require 'evil-org-agenda)

1. It can be used independently from `evil-org`.
2. It shouldn't be enabled on a require according to conventions: https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html

> What is gr?

If this is mapped to `org-agenda-redo`, it becomes consistent with evil-magit. Furthermore, Spacemacs also uses `gr` as a general shortcut for refreshing things. `org-agenda-redo` has nothing to do with `org-agenda-undo`.

> Adding options will increase the code complexity and its maintenance, while it is straightforward for the end users to tweak the bindings themselves. If they want f or t to do something different, it's just one or two lines in their init.el, which is just as much as toggling some dedicated option on/off :)

Not ideal, but if the options are systematic, it may have a benefit. For individual key bindings, it's probably not worth the effort.

**Comment by Somelauw** [comment]
Solved by https://github.com/Somelauw/evil-org-mode/pull/26
