### ISSUE TITLE
Void function 'obsolete' (prints message about RSI bindings)

### ISSUE THREAD

**Issue by ahungry** [Somelauw/evil-org-mode#17]
```
Debugger entered--Lisp error: (void-function obsolete)
  obsolete("Please create a github issue if you want to keep RSI bindings." "0.9.1")
```

So, here I am filing the issue - seems the obsolete call is not good.

Also, I'm not sure what the RSI bindings are, but it seems I may want to keep them :smile:

**Comment by Somelauw** [comment]
@ahungry thanks, you weren't supposed to get that void-function error. You can disable `rsi` for an easy workaround.

> Also, I'm not sure what the RSI bindings are, but it seems I may want to keep them 😄

It makes `C-d` and `C-f` promote/demote in Emacs mode when the pointer is at the end of a line. It's somewhat similar to `insert`, but works in 'emacs' mode. I stopped using these myself, but if others use them, I can deobsolete them.

**Comment by ahungry** [comment]
Haha, RSI mode, I get it now :smile: - I'll leave it disabled!
