### ISSUE TITLE
`g q l` (evil-fill-and-move) doesn't format a long list item

### ISSUE THREAD

**Issue by concretevitamin** [Somelauw/evil-org-mode#18]
Repro:
Under an orgmode headline, `SPC i l p` (for spacemacs; but otherwise any long line of text that goes beyond the current screen width would do) but don't format it. `S-i` to the line beginning then add `- ` (a minus sign, then a space) at the beginning of this long line. Then `g q l` failed.

This is unfortunately distinct from vim behavior.  In vim, the first line has the leading `- `(2 chars), and the subsequent lines are nicely formatted to have 2-char indent as well.

**Comment by duianto** [comment]
Confirmed

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 9341e1d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors emacs-lisp git helm markdown org spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by concretevitamin** [comment]
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html yaml auto-completion better-defaults emacs-lisp markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control python osx)
```

**Comment by duianto** [comment]
It might not be an evil-org issue, because it works with Emacs, evil mode and evil-org-mode:
(The evil and evil-org packages are installed with Spacemacs)
- Start Emacs with: `emacs --quick`
- `M-x` `package-initialize`
- `S-M-;` `(require 'evil)`
- `M-x` `evil-mode`
- `M-x` `evil-org-mode`
- open a new buffer `C-x b` `test`
- `M-x` `org-mode`
- Copy this and paste it in Emacs:
```
* headline
- Lorem ipsum dolor sit amet, consectetuer adipiscing elit.  Donec hendrerit tempor tellus.  Donec pretium posuere tellus.  Proin quam nisl, tincidunt et, mattis eget, convallis nec, purus.  Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.  Nulla posuere.  Donec vitae dolor.  Nullam tristique diam non turpis.  Cras placerat accumsan nulla.  Nullam rutrum.  Nam vestibulum accumsan nisl.
```
- Put the cursor on the `- Lorem ipsum...` line
- Press `g q l`
It results in this:
```
* headline
- Lorem ipsum dolor sit amet, consectetuer adipiscing elit.  Donec
  hendrerit tempor tellus.  Donec pretium posuere tellus.  Proin quam
  nisl, tincidunt et, mattis eget, convallis nec, purus.  Cum sociis
  natoque penatibus et magnis dis parturient montes, nascetur
  ridiculus mus.  Nulla posuere.  Donec vitae dolor.  Nullam tristique
  diam non turpis.  Cras placerat accumsan nulla.  Nullam rutrum.  Nam
  vestibulum accumsan nisl.
```

**Comment by Somelauw** [comment]
@duianto Isn't that the result you want?

@concretevitamin says
> In vim, the first line has the leading -(2 chars), and the subsequent lines are nicely formatted to have 2-char indent as well.

Isn't that what it looks like in Emacs too?

**Comment by concretevitamin** [comment]
@Somelauw -- @duianto's second comment actually stated that, the correct result could come from just evil-org-mode, but not directly from spacemacs.  

I filed https://github.com/syl20bnr/spacemacs/issues/9579.

**Comment by duianto** [comment]
@Somelauw We were discussing the issue in the spacemacs gitter chat, and `g q l` didn't format the line in spacemacs, so I tried with just Emacs + evil, and it worked, that made us think that it could be an evil-org issue.

But after this issue had been posted, I also tried it with Emacs + evil + evil-org, and that resulted in my comment, that it might not be an evil-org issue.

In fact It also started working in Spacemacs after restarting, and it works now, when I just tried it again, so it's unclear what caused the issue.

**Comment by Somelauw** [comment]
Thanks for clearing that up.

evil-org is not changing the mapping to `gq` and I'm not aware of any code in evil-org that could be of influence.
`gq` calls `evil-fill` which uses `fill-region` behind the scenes. This function is controlled by variables that are probably set by `org-mode`.

If it behinds differently some of the time, maybe some parts of org-mode haven't been loaded yet.
