### ISSUE TITLE
Ctrl-Return breaks current line in normal mode

### ISSUE THREAD

**Issue by amosbird** [Somelauw/evil-org-mode#20]
```
** sub header
test   case  
       ^ --- hit  ctrl-return here

ends up at

test

**  case
```

**Comment by Somelauw** [comment]
I'm unable to reproduce. I get the following instead:

```org-mode
** subheader
test   case
** 
```

- Are you using GUI Emacs? (in terminal Emacs `ctrl-return` doesn't work)
- Are you pressing this key in insert or normal state?
- Is `C-return` bound to `evil-org-insert-heading-respect-content-below`?

**Comment by amosbird** [comment]
Oh, right. The binding is switched to `M-RET` here. However, how can I make it add one more blank line when there is another header below?

```
** foo

test case <--- ctrl-return

**   <--- ends here
** bar
```

**Comment by Somelauw** [comment]
@amosbird For `M-ret`, you can set `org-M-RET-may-split-line` to `nil`.

**Comment by Somelauw** [comment]
I'm sorry for misreading your second question. I don't know if there is a way to make `C-return` insert an extra newline when there is a heading below, but I think such a feature is better left for org-mode itself, not for evil-org-mode.

**Comment by amosbird** [comment]
Hi, thanks for the reply. Ok, I think so too :)
