### ISSUE TITLE
dd does not trigger ordered list renumber

### ISSUE THREAD

**Issue by LindyBalboa** [Somelauw/evil-org-mode#22]
`dd` currently does not force a renumber and I think it is very intuitive that it should.

Running 25.3.1 on 64bit Arch Linux

**Comment by Somelauw** [comment]
@LindyBalboa Can you help test the following?

```emacs-lisp
(evil-define-operator evil-org-delete ()
  "Like evil-delete, but realigns tags and numbered lists."
  (interactive)
  (call-interactively #'evil-delete)
  (cond ((org-at-item-p)
         (org-list-repair))
        ((org-at-heading-p)
         (org-fix-tags-on-the-fly))))

(evil-define-key 'normal 'org-mode-map "d" #'evil-org-delete)
```

**Comment by LindyBalboa** [comment]
Seems to work out fine except the binding you gave should have no `'` on `org-mode-map` (I think)
`(evil-define-key 'normal org-mode-map "d" #'evil-org-delete)`
