### ISSUE TITLE
Text object for org babel

### ISSUE THREAD

**Issue by amosbird** [Somelauw/evil-org-mode#23]
Hi, it would be convenient to have text object help source code selection in babel env.

**Comment by Somelauw** [comment]
`vae` and `vaE` should both work on source code blocks.

**Comment by amosbird** [comment]
it selects the surrounding `   #+BEGIN_SRC      #+END_SRC` too

**Comment by Somelauw** [comment]
I agree that selecting the inside of a source code block is useful and I'm thinking of changing "ie" to do that.
I'm not yet sure what to do with "iE". Since that text object is similar to "ie" most of the time, I might change it so it selects the element without the final whitespace.

**Comment by Somelauw** [comment]
On https://github.com/Somelauw/evil-org-mode/pull/35 `ie` selects code blocks without begin and end. Let me know if this works for you.

**Comment by NightMachinary** [comment]
I think mentioning that `e` works with different kinds of "elements" in the readme will be useful to newcomers like myself. I thought it only works for headings.
