### ISSUE TITLE
Context sensitive HJKL

### ISSUE THREAD

**Issue by Ambrevar** [Somelauw/evil-org-mode#25]
Currently `shift` is a key theme because shift+movement would override Evil's `H`, `J`, `K` and `L`.
What about a context-sensitive compromise?
Namely:

```
(defun evil-org-shiftleft ()
  (interactive)
  ;; TODO: Use `org-at-heading-or-item-p' instead?
  (if (org-on-heading-p)
      (org-shiftleft)
    (evil-window-top)))

(defun evil-org-shiftright ()
  (interactive)
  (if (org-on-heading-p)
      (org-shiftright)
    (evil-window-bottom)))

(defun evil-org-shiftup ()
  (interactive)
  (if (org-on-heading-p)
      (org-shiftup)
    (evil-lookup)))

(defun evil-org-shiftdown ()
  (interactive)
  (if (org-on-heading-p)
      (org-shiftdown)
    (call-interactively 'evil-join)))
```

`evil-join` is rarely needed on headings, so we don't lose much here.
For the others, it's enough to move away from a header.  I think it's a good middle ground.

What's your take on this?

**Comment by Somelauw** [comment]
You can already customize it like that by adding hooks to the org-shift-commands.

See http://orgmode.org/manual/Conflicts.html

**Comment by Ambrevar** [comment]
Sure, my point was whether we could make this either an option, or the default for the `shift` theme.

**Comment by Ambrevar** [comment]
I'm happy to add it to the documentation, however I don't see [doc/example_config.el] available when the package is installed from MELPA?
Or is it referenced?  I'm asking since I did not know it existed.

What about moving the documentation to an .info file (like EMMS does) or to the wiki on GitHub?

**Comment by Somelauw** [comment]
I'm thinking of adding an option to make HJKL context-sensitive anyway but doing it in a flexible way and making it optional.

**Comment by Ambrevar** [comment]
Here is the code I've been using for a few weeks, works great for me so far.

```
(defun evil-org-meta-return ()
  "Like `org-meta-return' but switch to insert mode."
  (interactive)
  (evil-insert 1)
  (org-meta-return))

(defun evil-org-shiftleft ()
  (interactive)
  ;; TODO: Use `org-at-heading-or-item-p' instead?
  (if (or (org-on-heading-p) (org-at-planning-p))
      (org-shiftleft)
    (evil-window-top)))

; Repeat for right/up/down.
```

**Comment by Somelauw** [comment]
I think I found a satisfiable way to do this:
https://github.com/Somelauw/evil-org-mode/commit/1e64669cd65fc0f900a1166cfc4520f77aa5e41f

**Comment by Ambrevar** [comment]
Looks good to me, thanks!
