### ISSUE TITLE
evil-org-open-below only adds a list item when the cursor is on the line of the bullet itself

### ISSUE THREAD

**Issue by robbert-vdh** [Somelauw/evil-org-mode#31]
I'm not sure if this is intended behaviour or not, but pressing `o` in the following situation inserts a line break instead of opening a list item:

```
- Nunc aliquet, augue nec adipiscing interdum, lacus tellus malesuada massa,
  quis varius mi purus non odio. Nullam rutrum. Donec neque quam, dignissim in,
  mollis nec, sagittis eu, wisi. Etiam vel tortor sodales tellus ultricies
  commodo. Fusce sagittis, libero non molestie mollis, magna orci ultrices
  dolor, at vulputate neque nulla lacinia eros.█
```

This could probably be solved by using `org-in-item-p` instead of `org-at-item-p` in [evil-org-open-below](https://github.com/Somelauw/evil-org-mode/blob/22c248deb6c74a5bcdb0268306eed878a44fe517/evil-org.el#L253) and some other places, but again I'm not sure whether this was intentional or not.

**Comment by Somelauw** [comment]
This is intended.

My rationale is that if your item consists of multiple lines, you are more likely to want to insert a line in the middle than to split your item.
It's also possible to have code blocks and other elements in your item and in those cases, org-insert-item would create a new item in the middle of your code block.

**Comment by robbert-vdh** [comment]
Makes sense to me! Does evil-org-mode add any other ways to insert list items, or is `A M-RET` the way to go?

**Comment by Somelauw** [comment]
> Makes sense to me! Does evil-org-mode add any other ways to insert list items, or is A M-RET the way to go?

Perhaps there are a few cases in which `o` should insert a new item but currently doesn't. If so, feel free to suggest them.

evil-org doesn't provide another way to continue items. Well, there is the `return` keytheme but it triggers on the same conditions as `o`.
As far as I know, the only other ways to insert an item that work out of the box are `oM-RET` or typing a `-` by hand.
