### ISSUE TITLE
evil-org-> and < seem to have no effect in tables

### ISSUE THREAD

**Issue by dieggsy** [Somelauw/evil-org-mode#33]
The documentation (and source code) for `evil-org->` and `evil-org-<` imply that If I use them inside org tables, columuns will be moved in the right direction. The actual behavior I'm seeing is just that the whole table is indented.

**Comment by dieggsy** [comment]
It appears the second conditional:
```emacs-lisp
(save-excursion
           (goto-char beg)
           (<= (line-beginning-position) end (line-end-position)))
```
Is not actually returning true

**Comment by Somelauw** [comment]
Op dinsdag 13 februari 2018 heeft diego <notifications@github.com> het
volgende geschreven:
> It appears the second conditional:
>
> (save-excursion
> (goto-char beg)
> (<= (line-beginning-position) end (line-end-position)))
>
> Is not actually returning true
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/QkhL2Zodct0bO_5rKI2tAY5L49HwGTGSpRJ3cW7y5fUQyRmyzIIXRXmWSFZ7cnug4TFT0Hfm3UZyliAzOvCQ1x-BybEUoip4UzJ_qR5U93ugzLUsF3p_BS62rviANcWUdTFa3qgoijlO3SUJn8s-Oya0_kwlvA=s0-d-e1-ft#https://github.com/notifications/beacon/AA4Yu54-GMHiaQINaZ8f7U6YM9I9tGJOks5tURiEgaJpZM4SDOOr.gif
>

If `>>` is a used on a table line it moves the whole table. Same as `>ar`.
You can also use `=ar` to automatically indent.

If `>)` is used in a table cell, it will push the whole column to the
right. Same as `M-l` or `M-right`. This can be repeated by supplying a
COUNT.

**Comment by dieggsy** [comment]
Ah, ok. Thanks.
