### ISSUE TITLE
Strange behavior of `ie` on verbatim and code markup

### ISSUE THREAD

**Issue by sindikat** [Somelauw/evil-org-mode#34]
Enter the following text in your org-mode buffer.

    Foo *bar* baz *quux*.

    Foo =bar= baz =quux=.

    Foo /bar/ baz /quux/.

    Foo _bar_ baz _quux_.

    Foo ~bar~ baz ~quux~.

    Foo +bar+ baz +quux+.

Now try <kbd>die</kbd> key sequence on each `bar`. For markup `+` and `=` (which stand for code and verbatim respectively), <kbd>die</kbd> deletes the preceding text up to a previous paragraph, instead of just deleting contents inside markup. Deleting `quux`, however, works correctly.

**Comment by Somelauw** [comment]
For me, all "bar"s work, except \=\= and \~\~ which give an error.

**Comment by Somelauw** [comment]
Can you reproduce this issue on 
https://github.com/Somelauw/evil-org-mode/pull/35?
