### ISSUE TITLE
Updated use-package installation

### ISSUE THREAD

**Issue by wpcarro** [Somelauw/evil-org-mode#40]
The latest `use-package` exposes helpers around creating hooks. The installation in the Readme can be simplified to:

```elisp
(use-package evil-org
  :ensure t
  :after org
  :hook ((org-mode . evil-org-mode)
         (evil-org-mode . evil-org-set-key-theme))
  :config
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))
```

Also if users have `general.el` installed, the install can be further simplified to:

```elisp
(use-package evil-org
  :ensure t
  :after org
  :ghook 'org-mode-hook
  :gfhook #'evil-org-set-key-theme
  :config
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))
```

**Comment by Somelauw** [comment]
I want installation to be independent of general. `:hook` vs `add-hook` doesn't look like a big difference to me.
