### ISSUE TITLE
tag a new release?

### ISSUE THREAD

**Issue by unhammer** [Somelauw/evil-org-mode#48]
It seems https://github.com/Somelauw/evil-org-mode/tree/v0.1.1 is from 2014 :)

**Comment by 4lex1v** [comment]
Any chance to push 1.1 to melpa stable?

**Comment by Somelauw** [comment]
I can create a new release, once https://github.com/Somelauw/evil-org-mode/pull/60 is merged to master

**Comment by Somelauw** [comment]
a new release has been made
