### ISSUE TITLE
Keys in agenda bound only after opening it twice

### ISSUE THREAD

**Issue by manukall** [Somelauw/evil-org-mode#55]
Using the recommended use-package definition, keys in org-agenda aren't bound when opening it for the first time (`M-x org-agenda` and pressing `a`). Only after closing the buffer with `g` and opening it again in the same way can I navigate lines with `j` and `k`.

I guess `evil-org-agenda-set-keys` needs to be run before the agenda is opened to be effective.

**Comment by Somelauw** [comment]
Yes, see README for how to set it up
