### ISSUE TITLE
Error when trying to use text object

### ISSUE THREAD

**Issue by mrbig033** [Somelauw/evil-org-mode#56]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-11-28
- Evil version 1.2.14
- Evil Org Version: 20180323.2306
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_minimal)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_minimal/packs.el)

#### Use-package declaration

``` emacs-lisp
(use-package evil-org
  :ensure t
  :after org
  :config
  (add-hook 'org-mode-hook 'evil-org-mode)
  (add-hook 'evil-org-mode-hook
            (lambda ()
              (evil-org-set-key-theme)))
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))
```

#### Issue
Whenever I run the command `vie` in `normal mode` to select an inner element, the command fails and I get the following message:

`evil-org-select-inner-element: Symbol’s function definition is void: s-ends-with\?`

**Comment by ChanderG** [comment]
Hey, I had the same issue, #53. 

Solution is to add (require 's) for the s package that provides the s-* functions.

**Comment by Somelauw** [comment]
There is only one use of `s` in the entire package. Instead of requiring `s` I'll replace it by a native function.
