### ISSUE TITLE
Opening links in normal mode

### ISSUE THREAD

**Issue by ambihelical** [Somelauw/evil-org-mode#57]
I would like RET to follow capture file links in normal mode.   It seems like evil-org-return will do it, but it's only bound in insert mode or in emacs mode.   The binding in normal mode is evil-return, which doesn't follow capture links, at least with my current config.  Is there a way to make this happen?

**Comment by Somelauw** [comment]
Probably best to just exclude `evil-return` from your evil config, because by default it mostly performs the same action as `j`.

```
(define-key evil-motion-state-map (kbd "RET") nil)
```

The same for `tab`, `space` and `backspace` by the way.
