### ISSUE TITLE
:w doesn't work anymore in org src buffers

### ISSUE THREAD

**Issue by jackkamm** [Somelauw/evil-org-mode#59]
At some point in the past `:w` in an org src buffer would update and save the underlying org-file, but this hasn't worked for some time now, and now throws `user-error: Please specify a file name for the buffer`.

The following binding (suggested in https://github.com/Somelauw/evil-org-mode/issues/43) adds this feature back:
```
(define-key org-src-mode-map [remap evil-write] 'org-edit-src-save)
```

I'm using `org-plus-contrib-20190624` and `evil-org-20180323.2306`.

**Comment by Somelauw** [comment]
`ZZ` works for me. Otherwise `C-c C-c` isn't too bad.
However, if anyone should attempt to fix this, be sure that it doesn't break `:w newfile.org`.

**Comment by Somelauw** [comment]
See https://github.com/Somelauw/evil-org-mode/issues/43
