### ISSUE TITLE
Default for org files?

### ISSUE THREAD

**Issue by kirkins** [Somelauw/evil-org-mode#62]
I've added the snippet in the README to my `~/.emacs` file.

When I open an org file it seems to default to normal `org-mode` with `evil-mode` enabled.

I have to switch off `evil-mode` and then switch on `evil-org`.

Installed via MELPA. Not sure if it's a bug on my end or the feature isn't there yet?

**Comment by Somelauw** [comment]
@kirkins Does this still happen after https://github.com/Somelauw/evil-org-mode/pull/80 ?

**Comment by Somelauw** [comment]
Please reopen if this issue shows up again

**Comment by hwesterholt** [comment]
I know that this issue has been closed for a while, but I have the exact same problem. I also use `evil-collection`, could this be clashing with `evil-org`?
