### ISSUE TITLE
[BUG] Wrong behavior for C-v and $

### ISSUE THREAD

**Issue by WhatDothLife** [Somelauw/evil-org-mode#63]
##### Consider the following excerpt from an org file:

```
medium line
much longer line
short line
```

When I enter the visual block selection in the first line, move two lines down and then press `$`, only a rectangular region is marked instead of until the end of all three lines.

This is a different behavior compared to the one implemented in evil and vim.

**Comment by Somelauw** [comment]
I agree the behaviour is different from pure vim/evil. I mostly try to combine the best of both worlds, for example `I` works different from evil when `org-special-ctrl-a/e` is true. `$` also has some differences and by default works on visual line.

Do you think the evil behaviour (selection all lines) is strictly better and needs to select the whole line?

**Comment by WhatDothLife** [comment]
I think it would be more consistent to stick with the default behavior of `$`. To select visual lines there is still `g$` to achieve the desired behavior.

**Comment by WhatDothLife** [comment]
Also, pressing `C-v` and moving two lines down results in the selection seen below. What is the reason for this behavior?
![evil-org](https://user-images.githubusercontent.com/33008303/71772473-93fb6400-2f4b-11ea-9173-d468b8b71a2b.png)

**Comment by Somelauw** [comment]
> Also, pressing C-v and moving two lines down results in the selection
seen below. What is the reason for this behavior?

That is probably due to `org-bullets`. Anyway, I don't do anything to
`C-v`, only `$` is modified so it stops before folded lines.
