### ISSUE TITLE
promote and demote causing Emacs 27.0.50 to hang

### ISSUE THREAD

**Issue by jsmestad** [Somelauw/evil-org-mode#64]
I have not been able to debug as `C-g` cannot interupt the command. Has anyone else run into this and have any workaround?

Same functionality works fine with Emacs 26.3

**Comment by Somelauw** [comment]
Do you have steps to reproduce this?

On Monday, 16 December 2019, Justin Smestad <notifications@github.com>
wrote:
> I have not been able to debug as C-g cannot interupt the command. Has
anyone else run into this and have any workaround?
>
> Same functionality works fine with Emacs 26.3
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/wM5admzXMTyAKnUSTkPdle_LjX_YPVzHN1MuMrq_q85vHu7eTpMDpncd7Tjy0jn1f8zag2Y6ggOSZ1CNWAZsnTZ94ozin2dT-tstMKVBM9zA4SeUGNliFfWGDkOQr7RopohTHRowFrZ0en2UcdFBQS5s8H9Snoj6YRUH3xVA_d5i_E-QntB6_v1uGIJfZFns9KoccyNyeMeVpMqv7Lj7AJJsvQg=s0-d-e1-ft#https://github.com/notifications/beacon/AAHBROY5HCN5TYEU7II5JB3QY7BHRA5CNFSM4J3N7H4KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IA2ALDA.gif>

**Comment by jsmestad** [comment]
So I did more digging into this and my config uses quite a few settings from `doom-emacs` which has an open bug trying to track the issue down.

Maybe you want to look and see what the outcome there is. It may be worth mentioning it in the README for others? https://github.com/hlissner/doom-emacs/issues/894
