### ISSUE TITLE
zt, zz, and zb are not possible in org-agenda mode.

### ISSUE THREAD

**Issue by crocket** [Somelauw/evil-org-mode#65]
Instead, `z` is bound to org-agenda-view-mode-dispatch, so I cannot press `zt`, `zz`, `zb`, and other keystrokes starting with `z`.

**Comment by Somelauw** [comment]
@crocket This mode does override a few evil standards. I'm mostly willing to conform to follow standards set by evil-collection on this.

Please discuss with @Ambrevar or make an issue on https://github.com/emacs-evil/evil-collection/issues

**Comment by crocket** [comment]
evil-org-mode is separate from evil-collection.

**Comment by crocket** [comment]
I created https://github.com/emacs-evil/evil-collection/issues/292

**Comment by crocket** [comment]
What about binding

* `gzt` to `evil-scroll-line-to-top`
* `gzz` to 'evil-scroll-line-to-center'
* `gzb` to `evil-scroll-line-to-bottom`

**Comment by crocket** [comment]
evil-colleciton now binds `zb` to `evil-scroll-line-to-bottom` on outline mode..

**Comment by crocket** [comment]
I propose moving `z` to `Z`.

**Comment by crocket** [comment]
I think this is fixed.
