### ISSUE TITLE
Key bindings are not available until state transition and are overridden.

### ISSUE THREAD

**Issue by crocket** [Somelauw/evil-org-mode#73]
Both README.org and doc/keythemes.org don't explain that navigation bindings are available only in motion mode.

I'd want to have navigation bindings in normal mode, too.

**Comment by Somelauw** [comment]
Unless evil has changed considerably, normal mode inherits from motion state.
So I don't understand why these keys aren't available to you.

normal/visual mode both inherit from motion mode.

**Comment by crocket** [comment]
Navigation keys becomes available once I enter insert mode and go back to normal mode.

**Comment by crocket** [comment]
Additional keys become available only after I enter insert mode and come back to normal mode.

**Comment by crocket** [comment]
In my org mode, normal state keybinding from some other elisp scripts overrides motion state keybinding.

**Comment by crocket** [comment]
Somehow, `g k` is bound to `org-backward-heading-same-level` instead of `org-backward-element`.

**Comment by crocket** [comment]
I traced the problem back to

```
(define-key org-mode-map [remap outline-backward-same-level]
  #'org-backward-heading-same-level)
```

in `org-keys.el` from `org-plus-contrib`.

**Comment by crocket** [comment]
I think this issue is https://github.com/emacs-evil/evil/issues/301

**Comment by crocket** [comment]
Calling `(evil-normalize-keymaps)` after calling `(evil-org-mode)` in `org-mode-hook` fixes half of the issue.
However, bindings in `org-keys.el` still overrides evil-org bindings.

**Comment by crocket** [comment]
I think you should call `(evil-define-minor-mode-key 'motion 'evil-org ...)` or `(evil-define-key 'motion `evil-org ...)` in `evil-org.el`.

**Comment by crocket** [comment]
`evil-collection-outline.el` overrides `gk` on motion mode from `evil-org-mode` with `gk` on normal mode.
