### ISSUE TITLE
Problem with evil-org-open-links

### ISSUE THREAD

**Issue by EFLS** [Somelauw/evil-org-mode#76]
When calling `evil-org-open-links` on a region with multiple links, I get:

    evil-org-open-links: Symbol’s value as variable is void: org-link-search-failed

I'm using emacs 26.3 and org 9.3.6

Apparently, the variable `org-link-search-failed` is now named `org-link--search-failed`.
No idea when that change occurred, but replacing this in the function `evil-org-generic-open-links` seemed to work.

**Comment by Somelauw** [comment]
The function evil-org-open-links is deprecated. I don't know if it should
be part of a plug-in that combines org with evil.

If there is a different plugin that handles opening links better, it's
better to use that.
