### ISSUE TITLE
Incorrect `evil-org-delete` behaviour when using the `f<SPC>` suffix

### ISSUE THREAD

**Issue by polaris64** [Somelauw/evil-org-mode#78]
This issue was identified in Doom Emacs which uses [https://github.com/hlissner/evil-org-mode](https://github.com/hlissner/evil-org-mode) instead. However I am [duplicating the issue](https://github.com/hlissner/evil-org-mode/issues/4#issue-671106433) here in case it is a problem with this upstream repo.

Original issue description: -

When in a non-org buffer such as a fundamental buffer and using `df<SPC>` to delete up to and including the next space character, everything works as expected and in the same way that Vim works. However when in an Org mode buffer, using the same sequence deletes everything up to but not including the next space character.

Please note that `df<SPC>` denotes the sequence `df` followed by a press of the space bar.

As an example, consider the following sentence, where the pipe symbols denote the current point (on the letter "a"):

```
This is |a|n example.
```

If this is a non-org buffer then the result of `df<SPC>` will be:

```
This is example.
```

However doing exactly the same in an Org mode buffer produces:

```
This is  example.
```

(note the two spaces after "is").

This appears to be an issue with `evil-org-delete` which is not present in the base `evil-delete`.

**Comment by Somelauw** [comment]
I just tried creating an empty file having just:

```
This is |a|n example
```

And for me `df<SPC>` does produce:

```
This is |e|xample
```

`evil-org-delete` often falls back on standard `evil-delete`, but has special behaviour in certain contexts.

**Comment by polaris64** [comment]
Was that in an org-mode buffer? For me I get the extra space only under certain circumstances (such as that) which seems to be incorrect behaviour to me.
