### ISSUE TITLE
Using `o` and `O` throws error

### ISSUE THREAD

**Issue by dragsubil** [Somelauw/evil-org-mode#8]
When trying to use `o` and `O` (I haven't changed their default bindings from `evil-org-open-below`
and `evil-org-open-above`), I am getting the following error:

```
Symbol's function definition is void: case
```

My Emacs version is 24.5.1

**Comment by Somelauw** [comment]
Thanks for reporting. That should be fixed now.

**Comment by dragsubil** [comment]
Cool! Thank you for your work!
