### ISSUE TITLE
`z' was not bound to tweak display in org-agenda anymore

### ISSUE THREAD

**Issue by tshu-w** [Somelauw/evil-org-mode#82]
<img width="946" alt="Screen Shot 2020-09-21 at 10 41 44 AM" src="https://user-images.githubusercontent.com/13161779/93729438-0c4ba780-fbf7-11ea-9020-4827258b29b4.png">

### config to reproduce:
```emacs-lisp
;;; emacs -nw -Q -l ~/.emacs.d/test.el

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org"   . "https://orgmode.org/elpa/")
                         ("gnu"   . "https://elpa.gnu.org/packages/")))

;; initialize packages
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil)          ; To prevent initializing twice
  (package-initialize))

;; setup `use-package'
(unless (package-installed-p 'use-package)
  (when (not package-archive-contents)
    (package-refresh-contents))
  (package-install 'use-package))

(require 'use-package)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(use-package evil
  :ensure t
  :init
  (evil-mode))

(require 'evil-org)
(add-hook 'org-mode-hook 'evil-org-mode)
(evil-org-set-key-theme '(navigation insert textobjects additional calendar))
(require 'evil-org-agenda)
(evil-org-agenda-set-keys)
```
### Version info
evil-org 20200913.2124
GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G2021)) of 2020-08-25
macOS 10.15.6

**Comment by Somelauw** [comment]
It has moved to `gD` in https://github.com/Somelauw/evil-org-mode/issues/65

**Comment by Somelauw** [comment]
It has moved to `gD` in https://github.com/Somelauw/evil-org-mode/issues/65

**Comment by Somelauw** [comment]
It has moved to `gD` in https://github.com/Somelauw/evil-org-mode/issues/65

**Comment by tshu-w** [comment]
@Somelauw Thx, I got it, maybe we should change in README.org?

**Comment by Somelauw** [comment]
You're right. The readme should be updated. I'll reopen for that.

**Comment by crocket** [comment]
I forgot to update README. You should also add other keys like gH, gM, and gL to README.

**Comment by crocket** [comment]
https://github.com/Somelauw/evil-org-mode/pull/83
