### ISSUE TITLE
`org-agenda-later` and `org-agenda-earlier` keybindings no longer work

### ISSUE THREAD

**Issue by japhir** [Somelauw/evil-org-mode#86]
Recently I can't move forward and backward in the org-agenda anymore with <kbd>[</kbd> and <kbd>]</kbd>.

Did I do something wrong in [my config](https://github.com/japhir/ArchConfigs/blob/master/myinit.org#evil-org)?

**Comment by wailedpancakes** [comment]
I'm using the default use-package config and I'm also unable to move forward and backwards with `[` or `]`.

**Comment by wailedpancakes** [comment]
It still wasn't working for me so I explicitly called these keybindings in my init.el and it worked. Don't know why it's not working without doing this though.
`(evil-define-key 'motion 'org-agenda-mode-map (kbd "[") 'org-agenda-earlier)
(evil-define-key 'motion 'org-agenda-mode-map (kbd "]") 'org-agenda-later)
`

**Comment by mstine** [comment]
same issue here - @wailedpancakes solution worked for me

**Comment by cantao** [comment]
Same here!

**Comment by husainaloos** [comment]
I have the same problem. It appears that this because it is being mapped by `evil-collection`. When I look up at the current key-mappings I see the following:

```
`evil-collection-unimpaired-mode' Minor Mode Bindings:
key             binding
---             -------

[               Prefix Command
]               Prefix Command

] u             evil-collection-unimpaired-url-decode

[ u             evil-collection-unimpaired-url-encode

```

**Comment by husainaloos** [comment]
#88 appears to be a possible fix. It will remap the functionality to `[[` and `]]`. I am not sure if the author of package is active or not as it has not been merged for 3 weeks.

**Comment by Somelauw** [comment]
#88 has been accepted
