### ISSUE TITLE
Feature request: unset scheduled and deadline

### ISSUE THREAD

**Issue by mwip** [Somelauw/evil-org-mode#87]
One feature I am missing form this awesome package is the ability to unset scheduled times and deadlines. In vanilla org-mode this would be done with `C-u C-c C-s` and `C-u C-c C-d`, respectively. Since I `(setq evil-want-C-u-scroll t)`, I have to locally deactivate evil using `C-z` for invoking this. 

Is there any chance to include this in the evil key bindings. Or, in case I totally missed it, would it be useful to include it in the documentation?

Thanks!

**Comment by EFLS** [comment]
I think your problem is a more general one. How do you invoke universal arguments for other types of commands?

If you use space as a leader key, you could bind `SPC u` to `(universal-argument)` -- similar to how Spacemacs does it.

**Comment by mwip** [comment]
Thank you, that solves my issue.
