### ISSUE TITLE
`evil-redirect-digit-argument` removed from evil

### ISSUE THREAD

**Issue by sballert** [Somelauw/evil-org-mode#93]
Hi, I get the following error message when I try to execute a command from org-mode:

```
evil-org--populate-base-bindings: Symbol’s function definition is void: evil-redirect-digit-argument
```

I think this issue results from the following evil mode change:

https://github.com/emacs-evil/evil/pull/1519

This commit removes the `evil-redirect-digit-argument` function from evil.

**Comment by Somelauw** [comment]
Solved by https://github.com/Somelauw/evil-org-mode/pull/96
